= Bewerbung für eine Ausbildung zum Fachinformatiker für Systemintegration

Datum: 25. Januar 2025

Stadtwerke Halle GmbH Personalabteilung

Bornknechtstraße 506108 Halle (Saale)


Sehr geehrte Damen und Herren,

mit großem Interesse habe ich auf Ihrer Website die Ausschreibung für eine Ausbildung zum Fachinformatiker für Anwendungsentwicklung gelesen. Ihr Unternehmen, als zentraler Dienstleister der Stadt Halle, steht für Verlässlichkeit und nachhaltige Entwicklung — Werte, die mich begeistern und motivieren, Teil Ihres Teams zu werden.

Während meiner schulischen Laufbahn habe ich meine Begeisterung für Informatik und Softwareentwicklung entdeckt. In meiner Freizeit programmiere ich kleine Anwendungen, durch die ich Erfahrungen mit Programmiersprachen wie C(++), Java, JavaScript und Kotlin sammeln konnte. Einige Beispiele hierfür sehen Sie auch in meinem verlinkten GithubRepository.
Mein Interesse in der Informatik entstand aus dem Wunsch heraus Probleme zu lösen. Sowohl meine eigen, als auch die anderer Menschen. Genau dieses Ziel sehe ich bei den Stadtwerken Halle im Fokus.

Ich bringe eine schnelle Auffassungsgabe, eine hohe Lernbereitschaft sowie eine strukturierte Arbeitsweise mit. Teamarbeit liegt mir besonders, wie ich durch verschiedene schulische und private Projekte unter Beweis stellen konnte. Gleichzeitig bin ich in der Lage, selbstständig und zuverlässig zu arbeiten und freue mich darauf, mein Engagement und meine Begeisterung für die IT-Branche in Ihr Unternehmen einzubringen und während der Ausbildung wertvolle Praxiserfahrungen zu sammeln. Ein persönliches Gespräch bietet eine ideale Gelegenheit, mich näher vorzustellen und mehr über die Stadtwerke Halle zu erfahren.

Vielen Dank für Ihre Zeit und die Prüfung meiner Bewerbung.


Mit freundlichen Grüßen

Lukas Philipp Diettrich

[Deine Adresse][PLZ Ort][E-Mail-Adresse][Telefonnummer]